services:
  postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: om123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: